CREATE TABLE EMPLOYEE (
id UUID PRIMARY KEY,
name TEXT NOT NULL,
surname TEXT NOT NULL,
age INTEGER NOT NULL,
gender TEXT NOT NULL);

CREATE TABLE DEPARTMENT (
id UUID PRIMARY KEY,
name TEXT NOT NULL,
floor INTEGER NOT NULL
);

CREATE TABLE PROGRAMMINGLANGUAGE(
id UUID PRIMARY KEY,
name TEXT NOT NULL
);

CREATE TABLE EMPLOYEEPLACE (
id UUID PRIMARY KEY,
employee_id UUID REFERENCES EMPLOYEE (id)  NOT NULL,
department_id UUID REFERENCES DEPARTMENT (id) NOT NULL,
programminglanguage_id UUID REFERENCES  PROGRAMMINGLANGUAGE  NOT NULL
);